# Generated by Django 5.0.6 on 2024-05-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Francesinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('price', models.BigIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ingredients', models.ManyToManyField(related_name='ingredients', to='francesinhas.ingredients')),
            ],
        ),
    ]
