# Generated by Django 5.0.6 on 2024-05-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesinhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='francesinha',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
